const areaConstant = {
  GET_AREA_LIST_LOADING: "GET_AREA_LIST_LOADING",
  GET_AREA_LIST_SUCCESS: "GET_AREA_LIST_SUCCESS",
  GET_AREA_LIST_FAIL: "GET_AREA_LIST_FAIL",

  GET_AREA_LOADING: "GET_AREA_LOADING",
  GET_AREA_SUCCESS: "GET_AREA_SUCCESS",
  GET_AREA_FAIL: "GET_AREA_FAIL",

  CREATE_AREA_LOADING: "CREATE_AREA_LOADING",
  CREATE_AREA_SUCCESS: "CREATE_AREA_SUCCESS",
  CREATE_AREA_FAIL: "CREATE_AREA_FAIL",

  UPDATE_AREA_LOADING: "UPDATE_AREA_LOADING",
  UPDATE_AREA_SUCCESS: "UPDATE_AREA_SUCCESS",
  UPDATE_AREA_FAIL: "UPDATE_AREA_FAIL",

  DELETE_AREA_LOADING: "DELETE_AREA_LOADING",
  DELETE_AREA_SUCCESS: "DELETE_AREA_SUCCESS",
  DELETE_AREA_FAIL: "DELETE_AREA_FAIL",
};

export default areaConstant;