const deviceConstant = {
  GET_DEVICE_LIST_LOADING: "GET_DEVICE_LIST_LOADING",
  GET_DEVICE_LIST_SUCCESS: "GET_DEVICE_LIST_SUCCESS",
  GET_DEVICE_LIST_FAIL: "GET_DEVICE_LIST_FAIL",

  GET_DEVICE_LOADING: "GET_DEVICE_LOADING",
  GET_DEVICE_SUCCESS: "GET_DEVICE_SUCCESS",
  GET_DEVICE_FAIL: "GET_DEVICE_FAIL",

  CREATE_DEVICE_LOADING: "CREATE_DEVICE_LOADING",
  CREATE_DEVICE_SUCCESS: "CREATE_DEVICE_SUCCESS",
  CREATE_DEVICE_FAIL: "CREATE_DEVICE_FAIL",

  UPDATE_DEVICE_LOADING: "UPDATE_DEVICE_LOADING",
  UPDATE_DEVICE_SUCCESS: "UPDATE_DEVICE_SUCCESS",
  UPDATE_DEVICE_FAIL: "UPDATE_DEVICE_FAIL",

  DELETE_DEVICE_LOADING: "DELETE_DEVICE_LOADING",
  DELETE_DEVICE_SUCCESS: "DELETE_DEVICE_SUCCESS",
  DELETE_DEVICE_FAIL: "DELETE_DEVICE_FAIL",
};

export default deviceConstant;