const measurementConstant = {
  GET_MEASUREMENT_LIST_LOADING: "GET_MEASUREMENT_LIST_LOADING",
  GET_MEASUREMENT_LIST_SUCCESS: "GET_MEASUREMENT_LIST_SUCCESS",
  GET_MEASUREMENT_LIST_FAIL: "GET_MEASUREMENT_LIST_FAIL",

  GET_MEASUREMENT_LOADING: "GET_MEASUREMENT_LOADING",
  GET_MEASUREMENT_SUCCESS: "GET_MEASUREMENT_SUCCESS",
  GET_MEASUREMENT_FAIL: "GET_MEASUREMENT_FAIL",

  CREATE_MEASUREMENT_LOADING: "CREATE_MEASUREMENT_LOADING",
  CREATE_MEASUREMENT_SUCCESS: "CREATE_MEASUREMENT_SUCCESS",
  CREATE_MEASUREMENT_FAIL: "CREATE_MEASUREMENT_FAIL",

  UPDATE_MEASUREMENT_LOADING: "UPDATE_MEASUREMENT_LOADING",
  UPDATE_MEASUREMENT_SUCCESS: "UPDATE_MEASUREMENT_SUCCESS",
  UPDATE_MEASUREMENT_FAIL: "UPDATE_MEASUREMENT_FAIL",

  DELETE_MEASUREMENT_LOADING: "DELETE_MEASUREMENT_LOADING",
  DELETE_MEASUREMENT_SUCCESS: "DELETE_MEASUREMENT_SUCCESS",
  DELETE_MEASUREMENT_FAIL: "DELETE_MEASUREMENT_FAIL",
};

export default measurementConstant;