const userConstant = {
  GET_USER_LIST_LOADING: "GET_USER_LIST_LOADING",
  GET_USER_LIST_SUCCESS: "GET_USER_LIST_SUCCESS",
  GET_USER_LIST_FAIL: "GET_USER_LIST_FAIL",

  GET_USER_LOADING: "GET_USER_LOADING",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAIL: "GET_USER_FAIL",

  GET_LOGGED_USER_LOADING: "GET_LOGGED_USER_LOADING",
  GET_LOGGED_USER_SUCCESS: "GET_LOGGED_USER_SUCCESS",
  GET_LOGGED_USER_FAIL: "GET_LOGGED_USER_FAIL",

  CREATE_USER_LOADING: "CREATE_USER_LOADING",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  UPDATE_USER_LOADING: "UPDATE_USER_LOADING",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAIL: "UPDATE_USER_FAIL",

  DELETE_USER_LOADING: "DELETE_USER_LOADING",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  LOGOUT: "LOGOUT",
};

export default userConstant;